server:
  port: 7001
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:5001/eureka/
  instance:
    # 显示ip
    prefer-ip-address: true
    #  Status显示名
    instance-id: springcloud_consumer_7001
spring:
  application:
    # Application名称
    name: springcloud-consumer