server:
  # 服务器端口号
  port: ${PORT:5001}
eureka:
  instance:
    # 设置eureka实例名称
    hostname: eureka
  client:
    # 是否将自己注册到eureka-server中，默认为true
    register-with-eureka: false
    # 是否从eureka-server中获取服务注册信息，默认为true
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
# 应用程序服务名称
spring:
  application:
    name: eureka-server
    cloud:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/probeme/springcloud-config.git # GitHub上的Git仓库地址
          username: 1025037648@qq.com # git账号
          password: wangbin1994214  # git密码