server:
  port: 6003
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:5001/eureka/
  instance:
    #  显示ip
    prefer-ip-address: true
    #  Status显示名
    instance-id: springcloud_provider_6003
spring:
  application:
    # Application名称
    name: springcloud-provider-prod

